name: "Fan Speed Predictor"
description: "Predicts fan speed based on temperature, humidity, and heart rate"
version: "1.8.0"
slug: "fan_speed_predictor"
init: false
arch:
  - armv7
  - aarch64
ports:
  48762/tcp: 48762
